spring:
  main:
    web-application-type: none
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:file:${DB_PATH}
  jpa:
    show-sql: true
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;FILE_LOCK=NO;MODE=LEGACY
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: update

