CREATE TABLE IF NOT EXISTS WALLET
(
    ID          INTEGER NOT NULL,
    PRIVATE_KEY BLOB(2k)    NOT NULL,
    PUBLIC_KEY  BLOB(2k)    NOT NULL,
    PRIMARY KEY (ID)
);

create sequence SEQ_BLOCKCHAIN start with 1 increment by 1;

--drop table BLOCKCHAIN;
CREATE TABLE IF NOT EXISTS BLOCKCHAIN
(
    LEDGER_ID     INTEGER NOT NULL UNIQUE,
    PREVIOUS_HASH BLOB(2k)    NOT NULL,
    CURRENT_HASH  BLOB(2k)    , -- need to save to get ID. TODO: fix this
    CREATED_ON    TEXT,
    CREATED_BY    BLOB(2k),
    MINING_POINTS TEXT,
    LUCK          NUMERIC,
    PRIMARY KEY (LEDGER_ID)
);

--drop table TRANSACTIONS;
CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
    ID         VARCHAR2(36) NOT NULL,
    FROM_W     BLOB(2k),
    TO_W       BLOB(2k),
    LEDGER_ID  INTEGER,
    VALUE_V    INTEGER,
    SIGNATURE  BLOB    NOT NULL,
    CREATED_ON TEXT,
    PRIMARY KEY (ID)
);

